kind: CivoKubernetes
apiVersion: cluster.civo.crossplane.io/v1alpha1
metadata: 
  name: true-infra-provision
spec:
  name: true-infra-provision
  pools:
    - id: "8382e422-dcdd-461f-afb4-2ab67f171c3e"
      count: 2
      size: g3.k3s.small
    - id: "8482f422-dcdd-461g-afb4-2ab67f171c3e"
      count: 1
      size: g3.k3s.small
  applications: 
  # To remove default installed application
  # - "-Traefik"
  # - "-metrics-server"
  connectionDetails:
    connectionSecretNamePrefix: "cluster-details"
    connectionSecretNamespace: "default"
  providerConfigRef:
    name: civo-provider
